### ISSUE TITLE
formatBalance has incorrect formating

### ISSUE THREAD

**Issue by vikiival** [vue-polkadot/apps#109]
formatBalance filter has incorrect formating 

Expected
![Screen Shot 2020-07-13 at 13 38 23](https://user-images.githubusercontent.com/22471030/87300493-381f2280-c50e-11ea-8dd5-f720492645dc.png)

Current state
![Screen Shot 2020-07-13 at 13 38 17](https://user-images.githubusercontent.com/22471030/87300486-36555f00-c50e-11ea-8f41-50cc31ccb607.png)

value I get from api: `326666666602`

**Comment by vikiival** [comment]
Similar #63

**Comment by yangwao** [comment]
Looks like a case where @Ryan-Gordon fix #63 doesn't work 🤔

**Comment by vikiival** [comment]
fixed by f1b20c804fac50ecf4af46edbd8cdd2bb1bbdc9c
