### ISSUE TITLE
Move NFT module into separated project. 

### ISSUE THREAD

**Issue by vikiival** [vue-polkadot/apps#155]
Create project KodaNFT

**Comment by vikiival** [comment]
- [ ] Observe [NuxtJS](http://nuxtjs.org)
- [ ] Check if Nuxt is compatible with [TypeScript](http://typescript.nuxtjs.org)
- [ ] Inspect [Nuxt-Buefy package](https://github.com/buefy/nuxt-buefy)
- [ ] Try [A-Frame](http://aframe.io)
- [ ] Make workaround for socket connection

**Comment by vikiival** [comment]
[Using A-Frame with Nuxt](https://github.com/nuxt/nuxt.js/issues/30)

**Comment by yangwao** [comment]
Seems the upcoming hacking session will be heavy, should I order a KFC bucket? 
![image](https://user-images.githubusercontent.com/5887929/104934038-f3d37a00-59a9-11eb-8bdb-f9834b2f60bd.png)

**Comment by vikiival** [comment]
> Seems the upcoming hacking session will be heavy, should I order a KFC bucket?


Sure and please add garlic sauce and replace 🍟 with 🌽

**Comment by yangwao** [comment]
Done https://github.com/kodadot/nft-gallery and redeployed from `rmrk-lite` branch
