### ISSUE TITLE
Dark mode for KodaDot

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#158]
Ok, it was about time to come. Looking forward have toggle to do that and make invert for user.

* https://github.com/buefy/buefy/issues/1861
* Using https://jenil.github.io/bulmaswatch/ ?
* https://github.com/jloh/bulma-prefers-dark

**Comment by vikiival** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by yangwao** [comment]
Closing in favour https://github.com/kodadot/nft-gallery/issues/152
