### ISSUE TITLE
When connecting to Kusama CC2 hosted by Parity in settings

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#27]
![image](https://user-images.githubusercontent.com/5887929/68118136-7b48e080-feff-11e9-96a1-3ae24d0ea503.png)

**Comment by yangwao** [comment]
Edgeware Testnet has similar error 
![image](https://user-images.githubusercontent.com/5887929/68118395-396c6a00-ff00-11e9-9e6a-761176c3cbcd.png)

**Comment by vikiival** [comment]
Updated to vue-settings 0.0.9 which replaced CC2 with CC3
