### ISSUE TITLE
Update to recent Chain names 

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#36]
![image](https://user-images.githubusercontent.com/5887929/75687114-9b19c680-5c9d-11ea-8811-7e21eb5d1f57.png)

**Comment by vikiival** [comment]
`Did you publish correct branch ? `

<img width="1504" alt="Screen Shot 2020-03-02 at 19 06 39" src="https://user-images.githubusercontent.com/22471030/75704101-002ee580-5cb9-11ea-85ce-6cb3c4767a28.png">

**Comment by yangwao** [comment]
Already done in recent develop.
