### ISSUE TITLE
Create docker image 

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#51]
We would like to have a **docker image with UI running, for easier infrastructure setup.**

- [ ] Send PR against develop branch, beware, it breaks often, you might keep it up to date, till we merge it
- [ ] Include working Kusama network
- [ ] Working up-to-date image, [prefer one we are using here ](https://github.com/yangwao/kusama_playground)
- [ ] Working with local node, [inspiration](https://medium.com/@wilfried.kopp/your-very-own-local-polkadot-substrate-network-in-less-than-30s-1dd466f7f22b)
- [ ] Send screenshot with working local node & Kusama 
- [ ] It should be open to the local network as we are testing it from the mobile on the same WiFi.

Looking forward to contributing from outside. 🙌

**Comment by varit05** [comment]
@yangwao I am interested in the issue and can create a docker image. 

Please let me know if I can start working.

**Comment by yangwao** [comment]
@varit05 sure you can, but there isn't bounty placed on this issue. Are you willing to continue?

**Comment by varit05** [comment]
Well, Yes. I am interested so with or without bounty doesn't matter :)

**Comment by yangwao** [comment]
@varit05 cool, feel free to send PR! we would be glad to test it and accept it! :)

We had out of office last few weeks 😇

**Comment by Ryan-Gordon** [comment]
Interested in this

**Comment by yangwao** [comment]
done 

![image](https://user-images.githubusercontent.com/5887929/91070308-dc7ca480-e636-11ea-8ade-5aed1922c342.png)
