### ISSUE TITLE
Formated all values for Vue components from api

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#65]
Before we pass props to components, would be good to have formatted values.

So we can avoid using .toString() or parseInt() frequently.

**Comment by vikiival** [comment]
I think nice approach would be [Vue Filters](https://vuejs.org/v2/guide/filters.html)

**Comment by vikiival** [comment]
I started to code Vue filters and it's so easy to use check [Money component](https://github.com/vue-polkadot/apps/blob/treasury/dashboard/src/components/shared/format/Money.vue)


Only one problem is that we have small amount of formatting components.
