### ISSUE TITLE
The incorrect value of votes in the referendum

### ISSUE THREAD

**Issue by illlefr4u** [vue-polkadot/apps#67]
During referenda, the wrong value is displayed. The current value must be multiplied by 10 ^(-12).

screen in attach. Right value there is 18215 KSM
![vue_ps1](https://user-images.githubusercontent.com/21253681/79056639-f93bb100-7c2e-11ea-84ef-7461b57e0117.png)

**Comment by vikiival** [comment]
Hello,

thanks for submitting a issue. ✨ We will try to fix it in next release.

However the formula `10^(-12)` does not work for every substrate chain.
Some chains can use e.g 15 decimals.

We need to fetch tokenDecimals from `api.registry.getChainProperties()` and then multiply the referenum value with `10^(-tokenDecimals)`

**Comment by yangwao** [comment]
@vikiival I think this could be fixed in recent version thanks to chain properties in vuex 🤔

**Comment by vikiival** [comment]
Closed by f1b20c804fac50ecf4af46edbd8cdd2bb1bbdc9c
