### ISSUE TITLE
staking

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#7]
- [x] Staking overview
- [ ] Account actions
- [ ] Payouts
- [x] Targets
- [x] Waiting
- [ ] Validator stats - not sure in scope

**Comment by vikiival** [comment]
**Account Actions** : 

- [ ] New Nominator
- [ ] New Validator
- [ ] New Stash

**Comment by vikiival** [comment]
@yangwao Can you please check if Validator Stats are in scope ?
