### ISSUE TITLE
Sidebar postfixes before production release

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#77]
Adding look before replacing very own brewed sidebar with buefy sidebar. 
What's needs to be fixed before another release 

- [x]  white background for logo
- [x] dark theme with light (light-grey) icons
- [x] unfold button should be on the bottom to avoid wonky moving till we figure wrong alignment 
![image](https://user-images.githubusercontent.com/5887929/81186723-74388300-8fb3-11ea-806f-8588bd95726b.png)

**Comment by vikiival** [comment]
Fixed
